#!/bin/bash
#PBS -l ncpus=10
#PBS -l mem=100GB
#PBS -l jobfs=100GB
#PBS -q normal
#PBS -P ht96
#PBS -l walltime=24:00:00
#PBS -l storage=scratch/ht96+gdata/ht96



DIR=/g/data/ht96/Avneet_UQ/robin/bam_paths

ANGSD=/home/564/ak2993/angsd/

ANC=/g/data/ht96/Avneet_UQ/robin/reference/Senecio.contigs.fasta

for POP in G AG H01 D01 H02 D03 H05 D04

do

    echo $POP
    ${ANGSD}/angsd -b $DIR/$POP'_bams.txt' -anc $ANC -r tig00125552 -out /g/data/ht96/Avneet_UQ/robin/'thetas_'$POP/saf/$POP'_CONTIG_1' \
                   -remove_bads 1 \
                   -minMapQ 30 -minQ 20 -doCounts 1 \
                   -GL 2 -doSaf 1 -doMajorMinor 1 -nThreads 10 -underFlowProtect 1
done
