#!/bin/bash
#PBS -l ncpus=10
#PBS -l mem=100GB
#PBS -l jobfs=100GB
#PBS -q normal
#PBS -P ht96
#PBS -l walltime=10:00:00
#PBS -l storage=scratch/ht96+gdata/ht96


for POP in G AG H01 D01 H02 D03 H05 D04

do

    echo $POP
    /home/564/ak2993/angsd/misc/thetaStat do_stat /g/data/ht96/Avneet_UQ/robin/'thetas_'$POP/do_thetas/$POP'_CONTIG_1.thetas.idx' > /g/data/ht96/Avneet_UQ/robin/'thetas_'$POP/estimate_thetas/$POP'_CONTIG_1'
done
