#!/bin/bash
#PBS -l ncpus=10
#PBS -l mem=600GB
#PBS -l jobfs=550GB
#PBS -q hugemem
#PBS -P ht96
#PBS -l walltime=10:00:00
#PBS -l storage=scratch/ht96+gdata/ht96



DIR=/g/data/ht96/Avneet_UQ/robin/bam_paths

ANGSD=/home/564/ak2993/angsd/

ANC=/g/data/ht96/Avneet_UQ/robin/reference/Senecio.contigs.fasta

REGIONS=/g/data/ht96/Avneet_UQ/robin_genes/gene_regions/auxin_genes.txt
#doSaf because we don't want to filter on maf for thetas calculation
#only T watterson and Taj D are interpretable if anc is the ref genome

for POP in G AG H01 D01 H02 D03 H05 D04

do

    echo $POP
    ${ANGSD}/angsd -b $DIR/$POP'_bams.txt' -anc $ANC -rf $REGIONS -out /g/data/ht96/Avneet_UQ/robin_genes/'thetas_'$POP/saf/$POP'_GENES_auxin' \
                   -remove_bads 1 \
                   -minMapQ 30 -minQ 20 -doCounts 1 \
                   -GL 2 -doSaf 1 -doMajorMinor 1 -nThreads 10 -underFlowProtect 1
done
