#!/bin/bash
#PBS -l ncpus=10
#PBS -l mem=600GB
#PBS -l jobfs=550GB
#PBS -q hugemem
#PBS -P ht96
#PBS -l walltime=08:00:00
#PBS -l storage=scratch/ht96+gdata/ht96


for POP in G AG H01 D01 H02 D03 H05 D04

do

    echo $POP
    /home/564/ak2993/angsd/misc/realSFS /g/data/ht96/Avneet_UQ/robin_genes/'thetas_'$POP/saf/$POP'_GENES_auxin.saf.idx' -P 10 -maxIter 50 > /g/data/ht96/Avneet_UQ/robin_genes/'thetas_'$POP/sfs/$POP'_GENES_auxin.sfs'
done
