#!/bin/bash
#PBS -l ncpus=10
#PBS -l mem=600GB
#PBS -l jobfs=550GB
#PBS -q hugemem
#PBS -P ht96
#PBS -l walltime=10:00:00
#PBS -l storage=scratch/ht96+gdata/ht96



DIR=/g/data/ht96/Avneet_UQ/robin/bam_paths

ANGSD=/home/564/ak2993/angsd/

ANC=/g/data/ht96/Avneet_UQ/robin/reference/Senecio.contigs.fasta

REGIONS=/g/data/ht96/Avneet_UQ/robin_genes/gene_regions/auxin_genes.txt

for POP in G AG H01 D01 H02 D03 H05 D04

do

    echo $POP
     ${ANGSD}/angsd -P 10 -dosaf 1 -doThetas 1 -GL 2 -doMajorMinor 1 -underFlowProtect 1 \
                    -anc $ANC -rf $REGIONS -remove_bads 1 -minMapQ 30 -minQ 20 \
                    -b $DIR/$POP'_bams.txt' \
                    -pest /g/data/ht96/Avneet_UQ/robin_genes/'thetas_'$POP/sfs/$POP'_GENES_auxin'.sfs \
                    -out /g/data/ht96/Avneet_UQ/robin_genes/'thetas_'$POP/do_thetas/$POP'_GENES_auxin'
done
